#  Docker Notification Service CI/CD Pipeline
#  It will build, test, and deploy the Docker image for the Notification service
#  To deploy it u can use Render.com or any other service by uncommenting the relevant section
name: Build, Test, and Deploy Docker Image - Notification

on:
  push:
    tags:
      - "notification-v*"
    # Uncomment the following lines when we want to trigger on branch pushes as well
    # branches:
    #   - 'production'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: ./NOTIFICATION

     
      # - name: Run Unit Tests [ Pre-Deployment ]
      #   run: bun test
      #   working-directory: ./NOTIFICATION

      - name: Extract version or commit hash
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/notification-v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/notification-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./NOTIFICATION
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/studzee-notification:latest
            ${{ secrets.DOCKER_USERNAME }}/studzee-notification:${{ steps.version.outputs.VERSION }}

      # Trigger Render deploy hook ( uncomment when using Render.com )
      # - name: Trigger Render deploy hook
      #   run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_NOTIFICATION }}
